# General Configuration
num_rounds: 5
num_clients: 10
clients_per_round: ${num_clients}

server_batch_size: 16
load_server_data: true

# Client Configuration
client:
  epochs: 3
  lr: 0.001
  batch_size: 16

# # Adversarial Settings
# noise_rate: 1
# malicious_clients_ids: [0] # Malicious (also called faulty) client IDs (Ground Truth). Default client 0 is malicious.
# total_malicious_clients: null # For inducing multiple malicious clients in Table-2. e.g., 2 means clients [0, 1] are malicious

# # FedDebug Configuration
# feddebug:
#   fast: true # to generate randome inputs faster
#   r_inputs: 10 # number of random inputs to generate
#   na_t: 0.00 # neuron activation threshold

# Model Configuration
model: bert-base-cased #openai-community/openai-gpt # Options: lenet, resnet18, resnet34, resnet50, resnet101, resnet152, densenet121, vgg16

# Dataset Configuration
distribution: "iid" # Change to "iid" for iid data distribution. Change it to `non_iid` for non-iid data distribution.


column_of_label:
  yahoo_answers_topics: "topic"

column_of_text:
  yahoo_answers_topics: "question_content"

dataset_classes:
  yahoo_answers_topics: 10 # Text

dataset:
  name: yahoo_answers_topics
  num_classes: ${dataset_classes.${dataset.name}}
  label_column: ${column_of_label.${dataset.name}}
  text_column: ${column_of_text.${dataset.name}}
  max_length: 256
  

# Device and Resource Configuration
device: cpu
total_gpus: 1
total_cpus: 8

client_resources:
  num_cpus: 8
  num_gpus: 1 # Note that `num_gpus` is only used when the device is set to `cuda` (i.e., `device = cuda`)

# Logging Configuration (Hydra)
hydra:
  job_logging:
    root:
      level: INFO # Set the job logging level to INFO
    loggers:
      flwr:
        level: INFO
      accelerate.utils.other:
        level: ERROR
