# General Configuration
num_rounds: 1
num_clients: 2
clients_per_round: ${num_clients}

server_batch_size: 128
load_server_data: true

# Client Configuration
client:
  epochs: 1
  lr: 0.001
  batch_size: 64


# Dataset Configuration
distribution: "iid" #"iid" # Change to "iid" for iid data distribution. Change it to `non_iid` for non-iid data distribution.

column_of_label:
  yahoo_answers_topics: "topic"

column_of_text:
  yahoo_answers_topics: "question_content"

dataset_classes:
  yahoo_answers_topics: 10 # Text

dataset:
  name: yahoo_answers_topics
  num_classes: ${dataset_classes.${dataset.name}}
  label_column: ${column_of_label.${dataset.name}}
  text_column: ${column_of_text.${dataset.name}}
  max_length: 128

# Device and Resource Configuration
device: cuda
total_gpus: 1
total_cpus: 8

client_resources:
  num_cpus: 8
  num_gpus: 1 # Note that `num_gpus` is only used when the device is set to `cuda` (i.e., `device = cuda`)

# Logging Configuration (Hydra)
hydra:
  job_logging:
    root:
      level: INFO # Set the job logging level to INFO
    loggers:
      flwr:
        level: INFO
      accelerate.utils.other:
        level: ERROR

##### New Edition #####
peft_config:
  r: 8
  lora_alpha: 16
  lora_dropout: 0.1
  task_type: "SEQ_CLS"
  fan_in_fan_out: true

# Model Loading Configuration
model_config:
  name: openai-community/gpt2
  kwargs:
    use_cache: false
    trust_remote_code: true
    attn_implementation: "flash_attention_2"
    # torch_dtype: "bfloat16"
    device_map: null
    num_labels: ${dataset_classes.${dataset.name}}

  tokenizer:
    max_length: 2048
    use_fast: true

dir: "./checkpoint_dir"


peft: true
model: openai-community/gpt2 #openai-community/openai-gpt # Options: lenet, resnet18, resnet34, resnet50, resnet101, resnet152, densenet121, vgg16



# HF Trainer Configuration. This will be used by each client to train the model
hf_trainer_config:
  num_train_epochs: 0.001
  per_device_train_batch_size: 64
  per_device_eval_batch_size: 64

  # learning rate settings
  learning_rate: 5.0e-06
  lr_scheduler_type: cosine
  warmup_ratio: 0.2

  max_steps: -1
  gradient_accumulation_steps: 1

  # Optimization settings
  # bf16: true

  # logging
  output_dir: ${dir}
  # overwrite_output_dir: true
  save_steps: 0 #100
  save_total_limit: 0 # 1
  save_strategy: "no"

  logging_strategy: steps
  logging_steps: 20
  log_level: info
  # remove_unused_columns: true
  
