# General Configuration
num_rounds: 10
num_clients: 5
clients_per_round: ${num_clients}

server_batch_size: 128
load_server_data: true

# Client Configuration
client:
  epochs: 3
  lr: 0.001
  batch_size: 32

peft: true
model: openai-community/gpt2 #openai-community/openai-gpt # Options: lenet, resnet18, resnet34, resnet50, resnet101, resnet152, densenet121, vgg16

# Dataset Configuration
distribution: "iid" # Change to "iid" for iid data distribution. Change it to `non_iid` for non-iid data distribution.

column_of_label:
  yahoo_answers_topics: "topic"

column_of_text:
  yahoo_answers_topics: "question_content"

dataset_classes:
  yahoo_answers_topics: 10 # Text

dataset:
  name: yahoo_answers_topics
  num_classes: ${dataset_classes.${dataset.name}}
  label_column: ${column_of_label.${dataset.name}}
  text_column: ${column_of_text.${dataset.name}}
  max_length: 256

# Device and Resource Configuration
device: cuda
total_gpus: 1
total_cpus: 8

client_resources:
  num_cpus: 8
  num_gpus: 1 # Note that `num_gpus` is only used when the device is set to `cuda` (i.e., `device = cuda`)

# Logging Configuration (Hydra)
hydra:
  job_logging:
    root:
      level: INFO # Set the job logging level to INFO
    loggers:
      flwr:
        level: INFO
      accelerate.utils.other:
        level: ERROR
