train_config:
  num_train_epochs: 1
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4

  # learning rate settings
  learning_rate: 5.0e-06
  lr_scheduler_type: cosine
  warmup_ratio: 0.2

  max_seq_length: 1024
  packing: true

  max_steps: -1
  gradient_accumulation_steps: 1

  gradient_checkpointing: true
  gradient_checkpointing_kwargs:
    use_reentrant: false

  # Optimization settings
  bf16: true

  # logging
  output_dir: "./checkpoint_dir"
  overwrite_output_dir: true
  save_steps: 100
  save_total_limit: 0 # 1
  logging_strategy: steps
  logging_steps: 20
  log_level: info

  remove_unused_columns: true
  do_eval: false

# PEFT (Parameter Efficient Fine-Tuning) configurations
peft_config:
  r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  bias: "none"
  task_type: "CAUSAL_LM"
  target_modules: "all-linear"
  modules_to_save: null

# Model Loading Configuration
model_config:
  name: "microsoft/Phi-3-mini-4k-instruct"
  kwargs:
    use_cache: false
    trust_remote_code: true
    attn_implementation: "flash_attention_2"
    torch_dtype: "bfloat16"
    device_map:  null

  tokenizer:
    max_length: 2048
    use_fast: true




dataset_config:
  name: "HuggingFaceH4/ultrachat_200k"
  kwargs:


  
  