# Configuration for Federated Learning (FL) and Centralized Learning (CL) Setup

# =========================
# General Configuration
# =========================

experiment_key: "prov_1"

# ${oc.env:TMPFS} #

# Experiment Settings
experiment_directories:
  root_dir: _storage/ex1
  trainer_dir: ${experiment_directories.root_dir}/trainer_dir
  fl_cache_dir: ${experiment_directories.root_dir}/fl_cache



# =========================
# Federated Learning (FL) Configuration
# =========================
fl:
  num_rounds: 2
  num_clients: 2
  clients_per_round: 2

# =========================
# Training Configuration
# =========================
train:
  batch: 8
  ga: 1
  warmup_steps: 10
  max_steps: 200
  lr: 5e-5
  logging_steps: 5
  optim: "adamw_8bit"
  weight_decay: 0.01
  scheduler: "linear"
  seed: 3407
  output_dir: "outputs_federated"
  report_to: "none"

# =========================
# Model Configuration
# =========================
model:
  name: "unsloth/gemma-3-270m-it"
  max_seq_length: 2048
  load_in_4bit: false
  load_in_8bit: false

# =========================
# Dataset Configuration
# =========================
datasets:
  chess:
    name: "Thytu/ChessInstruct"
    split: "train[:10000]"
  math:
    name: "m-gopichand/deepmind_math_dataset_processed"
    split: "train[:10000]"
    filter_difficulty: "train-easy"
   




device: "cuda" # Options: "cuda", "cpu"

total_gpus: 2
total_cpus: 16

client_resources:
  num_cpus: 3 # if its more than  # clients x num_cpus> total_cpus, it will become sequential.
  num_gpus: 1 # Only relevant if device.type is "cuda"

# =========================
# Logging Configuration (Hydra)
# =========================
# Logging Configuration (Hydra)
hydra:
  job_logging:
    root:
      level: INFO # Set the job logging level to INFO
    loggers:
      flwr:
        level: INFO
      accelerate.utils.other:
        level: ERROR
# =========================
# Additional Configurations (Optional)
# =========================
# If you have other configurations or defaults, you can include them here.
